apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: a9s-default-user
rules:
- apiGroups:
  - authorization.k8s.io
  - certificates.k8s.io
  - extensions
  - metrics.k8s.io
  - node.k8s.io
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - authentication.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - scheduling.k8s.io
  - storage.k8s.io
  resources:
  - ""
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - storageclasses
  - persistentvolumes
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolesbinding
  verbs:
  - patch
  - watch
  - list
  - create
  - update
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - '*/scale'
  - componentstatuses
  - configmaps
  - namespaces
  - namespaces/finalize
  - namespaces/status
  - nodes
  - nodes/status
  - nodes/log
  - nodes/metrics
  - nodes/proxy
  - nodes/spec
  - nodes/stats
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  - controllerrevisions
  - cronjobs
  - cronjobs/finalizers
  - cronjobs/status
  - csidrivers
  - csinodes
  - customresourcedefinitions
  - daemonsets
  - daemonsets/finalizers
  - daemonsets/status
  - deployments
  - deployments/rollback
  - deployments/scale
  - deployments/status
  - deployments/finalizers
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  - ingresses
  - ingresses/status
  - jobs
  - jobs/finalizers
  - jobs/status
  - leases
  - limitranges
  - localsubjectaccessreviews
  - mutatingwebhookconfigurations
  - poddisruptionbudgets
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - runtimeclasses
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - secrets
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  - subjectaccessreviews
  - tokenreviews
  - trafficsplits
  - validatingwebhookconfigurations
  - volumeattachments
  - bindings
  - endpoints
  - endpoints/restricted
  - events
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - pods/eviction
  - pods/binding
  - pods/log
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/finalizers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  - persistentvolumeclaims/status
  - resourcequotas
  - resourcequotas/status
  - serviceaccounts
  - serviceaccounts/token
  - serviceprofiles
  - services
  - services/proxy
  - services/status
  - networkpolicies
  - priorityclasses
  verbs:
  - watch
  - list
- apiGroups:
  - extensions
  - apps
  resources:
  - replicationcontrollers/scale
  - controllerrevisions
  - deployments
  - deployments/rollback
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/finalizers
  - replicasets/scale
  - replicasets/status
  - ingresses
  - ingresses/status
  - daemonsets
  - daemonsets/status
  - statefulsets
  - statefulsets/finalizers
  - statefulsets/scale
  - statefulsets/status
  - networkpolicies
  verbs:
  - watch
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  - cronjobs
  - cronjobs/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - watch
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - get
  - watch
  - patch
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  verbs:
  - watch
  - list
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - caas-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
  - get
- apiGroups:
  - policy
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - list
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  - apiservices/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - watch
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - csinodes
  - volumeattachments
  - volumeattachments/status
  verbs:
  - watch
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - persistentvolumes
  - storageclasses
  verbs:
  - watch
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - watch
  - list
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - watch
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  verbs:
  - watch
  - list
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  - ingresses/status
  verbs:
  - watch
  - list
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - watch
  - list
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - watch
  - list
- apiGroups:
  - linkerd.io
  resources:
  - serviceprofiles
  verbs:
  - watch
  - list
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - watch
  - list
- apiGroups:
  - tap.linkerd.io
  resources:
  - deployments/tap
  verbs:
  - watch
  - list
